server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器(因为我本身就是客户端消费者，我不需要向你注册)
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

feign:
  hystrix:
    enabled: true # 开启服务熔断器

